# Generated by Django 4.2.7 on 2023-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
